# Generated by Django 5.2.4 on 2025-08-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(help_text="User's first name", max_length=30),
        ),
    ]
