# Generated by Django 5.2.4 on 2025-08-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_myuser_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="current_balance",
        ),
    ]
